apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-data-pvc
  namespace: seeksense
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

