apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-classifier
  namespace: seeksense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intent-classifier
  template:
    metadata:
      labels:
        app: intent-classifier
    spec:
      containers:
      - name: intent-classifier
        image: python:3.9-slim
        command:
        - "/bin/bash"
        - "-c"
        - |
          apt-get update && apt-get install -y git
          git clone https://github.com/ai-naymul/SeekSense.git
          cd SeekSense
          pip install -r requirements.txt
          python -m classification.intent_classification_server
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        env:
        - name: MODEL_NAME
          value: "csebuetnlp/banglabert_large"
---
apiVersion: v1
kind: Service
metadata:
  name: intent-classifier-service
  namespace: seeksense
spec:
  selector:
    app: intent-classifier
  ports:
  - port: 8001
    targetPort: 8001