apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data
  namespace: seeksense
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: seeksense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
      - name: milvus
        image: milvusdb/milvus:v2.2.8
        ports:
        - containerPort: 19530
        - containerPort: 9091
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        env:
        - name: ETCD_ENDPOINTS
          value: localhost:2379
        - name: MINIO_ADDRESS
          value: localhost:9000
        volumeMounts:
        - name: milvus-data
          mountPath: /var/lib/milvus
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.0
        ports:
        - containerPort: 2379
        command:
        - etcd
        - --data-dir=/etcd-data
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://localhost:2379
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
      - name: minio
        image: minio/minio:RELEASE.2023-07-21T21-12-44Z
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
        command:
        - minio
        - server
        - /data
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: milvus-data
        persistentVolumeClaim:
          claimName: milvus-data
      - name: etcd-data
        emptyDir: {}
      - name: minio-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  namespace: seeksense
spec:
  selector:
    app: milvus
  ports:
  - name: milvus
    port: 19530
    targetPort: 19530
  - name: metrics
    port: 9091
    targetPort: 9091