# values.yaml for SeekSense Helm chart
replicaCount: 1

image:
  repository: seeksense-app
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "3"
    memory: "6Gi"
    nvidia.com/gpu: "1" 
  requests:
    cpu: "1"
    memo# values.yaml for SeekSense Helm chart
    replicaCount:
      api: 2
      indexer: 1
      milvus: 1
    
    image:
      repository: seeksense
      tag: latest
      pullPolicy: IfNotPresent
    
    api:
      resources:
        limits:
          cpu: "1.5"
          memory: "3Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "500m"
          memory: "1Gi"
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 5
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
    
    indexer:
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "250m"
          memory: "512Mi"
    
    milvus:
      standalone:
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        persistence:
          enabled: true
          size: "5Gi"
    
    s3:
      bucketName: "your-s3-bucket-name"
      region: "us-east-1"
    
    secrets:
      apiKeys:
        jinaAI: "your-jina-ai-key"
      aws:
        accessKey: "your-aws-access-key"
        secretKey: "your-aws-secret-key"ry: "2Gi"

milvus:
  standalone:
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "0.5"
        memory: "1Gi"

secrets:
  apiKeys:
    jinaAI: "your-jina-ai-key"
    # Add other keys as needed

storage:
  s3:
    bucketName: "your-s3-bucket-name"
    region: "your-s3-region"
    # AWS credentials will be injected via environment variables